urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns

# Obszary kształcenia
urlpatterns = patterns('',
    (r'ea/assign/(?P<course_id>\d+)$', 'apps.trinity.views.ea.assign'),
    (r'ea/assign_phd/(?P<course_id>\d+)$', 'apps.trinity.views.ea.assign_phd'),
)

# Kierunkowe efekty kształcenia
urlpatterns += patterns('', 
    (r'clo/select-category/(?P<course_id>\d+)$', 'apps.trinity.views.clo.select_category'),
    (r'clo/show/(?P<course_id>\d+)/(?P<education_category_id>\d+)$', 'apps.trinity.views.clo.show'),
    (r'clo/add/(?P<course_id>\d+)/(?P<education_category_id>\d+)$', 'apps.trinity.views.clo.add'),
    (r'clo/update/(?P<course_id>\d+)/(?P<education_category_id>\d+)/(?P<clo_id>\d+)$', 'apps.trinity.views.clo.update'),
    (r'clo/delete/(?P<course_id>\d+)/(?P<education_category_id>\d+)$', 'apps.trinity.views.clo.delete'),
    (r'clo/print-pdf/(?P<course_id>\d+)/(?P<education_category_id>\d+)$', 'apps.trinity.views.clo.print_pdf'),
)

# Modułowe efekty kształcenia
urlpatterns += patterns('',  
    (r'mlo/select_sgroup/(?P<course_id>\d+)$', 'apps.trinity.views.mlo.select_sgroup'),
    (r'mlo/select-module/(?P<course_id>\d+)/(?P<sgroup_id>\d+)$', 'apps.trinity.views.mlo.select_module'),
    (r'mlo/show/(?P<course_id>\d+)/(?P<sgroup_id>\d+)/(?P<module_id>\d+)$', 'apps.trinity.views.mlo.show'),
    (r'mlo/add/(?P<course_id>\d+)/(?P<sgroup_id>\d+)/(?P<module_id>\d+)$', 'apps.trinity.views.mlo.add'),
    (r'mlo/update/(?P<course_id>\d+)/(?P<sgroup_id>\d+)/(?P<module_id>\d+)/(?P<mlo_id>\d+)$', 'apps.trinity.views.mlo.update'),
    (r'mlo/delete/(?P<course_id>\d+)/(?P<sgroup_id>\d+)/(?P<module_id>\d+)$', 'apps.trinity.views.mlo.delete'),
    (r'mlo/print-pdf/(?P<course_id>\d+)/(?P<sgroup_id>\d+)/(?P<module_id>\d+)$', 'apps.trinity.views.mlo.print_pdf'),
)

models.py
# -*- coding: utf-8 -*-

from django.db import models
from apps.syjon.lib.validators import validate_white_space
from django.utils.translation import ugettext_lazy as _

from apps.merovingian.models import Course, Module, CourseProfile
from apps.trainman.models import UserProfile


class TrinityProfile(models.Model):
    """
    Administrator efektów kształcenia.
    """
    class Meta:
        db_table = 'trinity_profile'
        verbose_name = _(u'Administrator')
        verbose_name_plural = _(u'Administrators')

    user_profile = models.OneToOneField(UserProfile, verbose_name=_(u'User'))
    courses = models.ManyToManyField(Course, db_table='trinity_profile__to__course', null=True, blank=True)
    
    def __unicode__(self):
        return self.user_profile.user.username
    
    @staticmethod
    def get_courses(user):
        if user.is_superuser:
            return Course.objects.active()
        else:
            return TrinityProfile.objects.get(user_profile=user.get_profile()).courses.filter(is_active=True)


class EducationArea(models.Model):
    """
    Obszar kształcenia.
    """
    class Meta:
        db_table = 'trinity_education_area'
        verbose_name = _(u'Area of education')
        verbose_name_plural = _(u'Areas of education')
        ordering = ['name']
        
    name = models.CharField(max_length=255)
    courses = models.ManyToManyField(Course, null=True, blank=True, db_table='trinity_education_area__to__course')
    
    def __unicode__(self):
        return self.name


class EducationCategory(models.Model):
    """
    Kategoria kształcenia.
    """
    class Meta:
        db_table = 'trinity_education_category'
        verbose_name = _(u'Education category')
        verbose_name_plural = _(u'Education categories')
        ordering = ['-name']
        
    name = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.name
    
#---------------------------------------------------
#--- KATEGORYZACJA KIERUNKÓW III STOPNIA
#---------------------------------------------------


class KnowledgeArea(models.Model):
    """
    Obszar wiedzy.
    """
    class Meta:
        db_table = 'trinity_knowledge_area'
        verbose_name = _(u'Area of knowledge')
        verbose_name_plural = _(u'Areas of knowledge')
        ordering = ['name']
        
    name = models.CharField(max_length=255)
    courses = models.ManyToManyField(Course, null=True, blank=True, db_table='trinity_knowledge_area__to__course')
    
    def __unicode__(self):
        return self.name   


class EducationField(models.Model):
    """
    Obszar nauki.
    """
    class Meta:
        db_table = 'trinity_education_field'
        verbose_name = _(u'Field of science')
        verbose_name_plural = _(u'Fields of science')
        ordering = ['area']
        
    name = models.CharField(max_length=255)
    area = models.ForeignKey('KnowledgeArea')
    discipline = models.ManyToManyField('EducationDiscipline', null=True, blank=True, db_table='trinity_education_field__to__education_discipline')
    courses = models.ManyToManyField(Course, null=True, blank=True, db_table='trinity_education_field__to__course')
    
    def __unicode__(self):
        return self.name


class EducationDiscipline(models.Model):
    """
    Dyscyplina nauki.
    """
    class Meta:
        db_table = 'trinity_education_discipline'
        verbose_name = _(u'Discipline of science')
        verbose_name_plural = _(u'Disciplines of science')
        ordering = ['name']
        
    name = models.CharField(max_length=255)
    courses = models.ManyToManyField(Course, null=True, blank=True, db_table='trinity_education_discipline__to__course')
    
    def __unicode__(self):
        return self.name

#---------------------------------------------------
#--- EFEKTY KSZTAŁCENIA
#--------------------------------------------------- 


class AreaLearningOutcome(models.Model):
    """
    Obszarowy efekt kształcenia.
    """
    class Meta:
        db_table = 'trinity_alo'
        verbose_name = _(u'Area learning outcome')
        verbose_name_plural = _(u'Area learning outcomes')
        ordering = ['symbol']

    symbol = models.CharField(max_length=16, validators=[validate_white_space])
    description = models.TextField(validators=[validate_white_space])
    education_area = models.ForeignKey('EducationArea')
    education_level = models.ForeignKey('merovingian.CourseLevel')
    education_profile = models.ForeignKey(CourseProfile)
    education_category = models.ForeignKey('EducationCategory')

    def __unicode__(self):
        return self.symbol


class CourseLearningOutcome(models.Model):
    """
    Kierunkowy efekt kształcenia.
    """
    class Meta:
        db_table = 'trinity_clo'
        verbose_name = _(u'Course learning outcome')
        verbose_name_plural = _(u'Course learning outcomes')
        ordering = ['symbol']

    course = models.ForeignKey(Course)
    education_category = models.ForeignKey('EducationCategory')
    symbol = models.CharField(max_length=16, validators=[validate_white_space])
    description = models.TextField(validators=[validate_white_space])
    alos = models.ManyToManyField('AreaLearningOutcome', db_table='trinity_clo__to__alo')
    
    def __unicode__(self):
        return self.symbol
    
    def get_related_modules(self):
        """
        Zwraca zbiór modułów powiązanych z kierunkowym efektem kształcenia.
        """
        return Module.objects.filter(modulelearningoutcome__clos=self).distinct()


class ModuleLearningOutcome(models.Model):
    """
    Modułowy efekt kształcenia.
    """
    class Meta:
        db_table = 'trinity_mlo'
        verbose_name = _(u'Module learning outcome')
        verbose_name_plural = _(u'Module learning outcomes')
        ordering = ['symbol']
    
    module = models.ForeignKey(Module)
    symbol = models.CharField(max_length=16, validators=[validate_white_space])
    description = models.TextField(validators=[validate_white_space])
    clos = models.ManyToManyField('CourseLearningOutcome', db_table='trinity_mlo__to__clo')
    
    def get_related_alos(self):
        """
        Zwraca zbiór obszarowych efketów kształcenia powiązanych z modułowym efektem kształcenia. Obszarowe efekty kształcenia powiązane są z modułowymi efektami kształcenia pośrednio przez kierunkowe efekty kształcenia.
        """
        return AreaLearningOutcome.objects.filter(courselearningoutcome__modulelearningoutcome=self).distinct()

    def __unicode__(self):
        return self.symbol

views/trinity.py
# -*- coding: utf-8 -*-

"""
-----------------------------------------------------------------
--- FUNKCJE POMOCNICZNE
-----------------------------------------------------------------
"""


def is_learning_outcomes_administrator(user, course):
    """
    Returns True if user can manage learning outcomes connected with specified speciality.
    @param user: User object
    @param course: Course object 
    """
    if user.is_superuser:
        return True
    
    is_administrator = False
    
    try:
        trinity_profile = user.get_profile().trinityprofile  # Gets user's learning outcomes administrator profile
        if course in trinity_profile.courses.all():  # Checkes if user has rights to speciality passed as a parameter
            is_administrator = True
    except:
        is_administrator = False
    
    return is_administrator

# -----------------------------------
# --- POTWIERDZENIE USUNIĘCIA
# -----------------------------------

from django.contrib.admin.util import NestedObjects
from django.utils.text import capfirst
from django.utils.encoding import force_text


def get_deleted_objects(objs):
    collector = NestedObjects(using='default')
    collector.collect(objs)

    def format_callback(obj):
        opts = obj._meta
        return '%s: %s' % (capfirst(unicode(opts.verbose_name)), force_text(obj))

    to_delete = collector.nested(format_callback)
    return to_delete

# -----------------------------------
# --- ZAPISYWANIE PLIKÓW PDF
# -----------------------------------


def mreplace(s, chararray, newchararray):
    """
    Zamienia wszystkie wystąpienia znaków w napisie s z tablicy chararray na odpowiednie wystąpienia w tablicy newchararray. 
    """
    for a, b in zip(chararray, newchararray):
        s = s.replace(a, b)
    return s


def utf2ascii(s):
    chararray = [u'ą', u'ć', u'ę', u'ł', u'ń', u'ó', u'ś', u'ź', u'ż', u'Ą', u'Ć', u'Ę', u'Ł', u'Ń', u'Ó', u'Ś', u'Ź', u'Ż']
    newchararray = [u'a', u'c', u'e', u'l', u'n', u'o', u's', u'z', u'z', u'A', u'C', u'E', u'L', u'N', u'O', u'S', u'Z', u'Z']
    return mreplace(s, chararray, newchararray)

templates/trinity/clo/add_update.html
{% extends "trinity/clo/show.html" %}

{% load i18n %}

{% block breadcrumb %}
	{{ block.super }}
	{% if clo %}
		&raquo; <a href="{% url apps.trinity.views.clo.update course_id=course.id education_category_id=education_category.id clo_id=clo.id %}">{% trans "Editing learning outcome for course" %}</a>
	{% else %}
		&raquo; <a href="{% url apps.trinity.views.clo.add course_id=course.id education_category_id=education_category.id %}">{% trans "Adding learning outcome for course" %}</a>
	{% endif %}
{% endblock %}

{% block content %}
	<h2>	
		{% if clo %}
			{% trans "Editing learning outcome for course" %}
		{% else %}
			{% trans "Adding learning outcome for course" %}
		{% endif %}
	</h2>
	
	{% block info %}
		{{ block.super }}
	{% endblock %}
	
	<div id="ee_add_edit">
        <form method="post" action="">
            {% csrf_token %}
			<h3>{% trans "Symbol" %}</h3>
            {{ form.symbol.errors }}
            {{ form.symbol }}
            <div class="spacer_10"></div>
            		
            <h3>{% trans "Description" %}</h3>
            {{ form.description.errors }}
            {{ form.description }}
            <div class="spacer_10"></div>
            
            {% if not course.is_level_phd and not course.is_level_pg_q and not course.is_level_pg_fl %}
	            <h3>{% trans "Learning outcomes for areas" %}</h3>
	            {{ form.learning_outcomes.errors }}
	            {{ form.learning_outcomes }}
	            <div class="spacer_10"></div>
	        {% endif %}
            
            <table class="table_0">
                <thead>
                    <tr>
                        <td>{% trans "Actions" %}</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <button class="button_2" type="submit" name="submit" value="save">{% trans "Save" %}</button>
                            {% if not clo %}
                            	<button class="button_2" type="submit" name="submit" value="save_and_continue">{% trans "Save and add" %}</button>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
{% endblock %}

templates/trinity/clo/print.html
{% extends "base_0p.html" %}

{% load i18n %}

{% block css %}
	<link rel="stylesheet" href="{{ STATIC_URL }}syjon/css/print.css" type="text/css" />
{% endblock %}

{% block body %}
<h4 style="text-align: center; margin-bottom: 30px;">{% trans "Course learning outcomes" %}</h4>
<table>
	<tr>
		<td class="label">{% trans "Course" %}: </td>
		<td><b>{{ course.name }}</b></td>
	</tr>
	<tr>
		<td class="label">{% trans "Level" %}: </td>
		<td>{{ course.level }}</td>
	</tr>
	<tr>
		<td class="label">{% trans "Type" %}: </td>
		<td>{{ course.type }}</td>
	</tr>
	<tr>
		<td class="label">{% trans "Profile" %}: </td>
		<td>{{ course.profile }}</td>
	</tr>
	<tr>
		<td class="label">{% trans "Year of didactic offer approval" %}: </td>
		<td>{{ course.start_date.year }}</td>
	</tr>
</table>

{% regroup clos by education_category as category_list %}
{% if category_list %}
	{% for category in category_list %}
		<h4 style="margin-top: 40px;">{% trans "Category" %}: {{ category.grouper }}</h4>
		<table>
			<thead style="text-align: center; font-weight: bold;">
				<tr class="header">
					<td>{% trans "Symbol" %}</td>
					<td>{% trans "Description" %}</td>
					{% if not course.is_level_phd and not course.is_level_pg_q and not course.is_level_pg_fl %}
						<td>{% trans "Area learning outcomes" %}</td>
					{% endif %}
					<td style="width: 220px;">{% trans "Modules" %}</td>
				</tr>
			</thead>
			<tbody>
				{% for clo in category.list %}
					<tr class="{% cycle 'odd' 'even' %}">
						<td class="center">{{ clo.symbol }}</td>
						<td>{{ clo.description }}</td>
						{% if not course.is_level_phd and not course.is_level_pg_q and not course.is_level_pg_fl %}
							<td>
								<ul>
									{% for alo in clo.alos.all %}
										<li>{{ alo }}</li>
									{% endfor %}	
								</ul>
							</td>
						{% endif %}
						<td>
							<ul>
								{% for module in clo.get_related_modules %}
									<li>{{ module }}</li>
								{% endfor %}	
							</ul>	
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
    {% endfor %}
{% else %}
    <p>{% trans "List of learning outcomes is empty." %}</p>
{% endif %}

{% endblock %}

templates/trinity/clo/select_category.html
{% extends "trinity/base.html" %}

{% load i18n %}

{% block breadcrumb %}
	{{ block.super }} 
	&raquo; <a href="{% url apps.trinity.views.clo.select_category course_id=course.id %}">{% trans "Choosing category of education" %}</a>
{% endblock %}

{% block content %} 
	<h2>{% trans "Choosing category of education" %}</h2>
	
	{% block info %}
	    <table class="table_0 no_cell_borders no_border">
	        <tbody>
	        	<tr><td class="label">{% trans "Course" %}:</td><td>{{ course }}</td></tr>
				{% if course.is_level_phd %}
	                <tr><td class="label">{% trans "Areas of knowledge" %}:</td><td>{{ course.knowledgearea_set.all|join:", " }}</td></tr>
	                <tr><td class="label">{% trans "Field of science or art" %}:</td><td>{{ course.educationfield_set.all|join:", " }}</td></tr>
	                <tr><td class="label">{% trans "Discipline of science or art" %}:</td><td>{{ course.educationdiscipline_set.all|join:", " }}</td></tr>
	            {% else %}
	                <tr><td class="label">{% trans "Area of education" %}:</td><td>{{ course.educationarea_set.all|join:", "|capfirst }}</td></tr>
	            {% endif %}
	        </tbody>
	    </table>
    {% endblock %}
    <div class="spacer_5"></div>

	<form action="" method="post">
		{{ form.non_field_errors }}
		<table class="table_0">
			{% csrf_token %}
			<thead>
				<tr>
					<td>{{ form.education_category.label }}</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{ form.education_category.errors }}{{ form.education_category }}</td>
				</tr>
			</tbody>
		</table>
		<div class="spacer_5"></div>
	
        <table class="table_0">
            <thead>
                <tr>
                    <td>{% trans "Actions" %}</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <button class="button_2" type="submit">{% trans "Next" %}</button>
                    </td>
                </tr>
            </tbody>
        </table>
	</form>
{% endblock %}

templates/trinity/clo/show.html
{% extends "trinity/clo/select_category.html" %}

{% load i18n lo_intensity %}

{% block breadcrumb %}
	{{ block.super }} 
	&raquo; <a href="{% url apps.trinity.views.clo.show course_id=course.id education_category_id=education_category.id %}">{% trans "Browsing course learning outcomes" %}</a>
{% endblock %}

{% block content %}
	<h2>{% trans "Browsing course learning outcomes" %}</h2>
    
    {% block info %}
    	{{ block.super }}
    	<table class="table_0 no_cell_borders no_border">
	        <tbody>
				<tr><td class="label">{% trans "Education category" %}:</td><td>{{ education_category|capfirst }}</td></tr>
	        </tbody>
	    </table>
	    <div class="spacer_5"></div>
    {% endblock %}

    <form method="post" action="{% url apps.trinity.views.clo.delete course_id=course.id education_category_id=education_category.id %}">
    	{% csrf_token %}
    	
	    {# TABELA Z PRZYCISKAMI #}
	    <table class="table_0">
	        <thead>
	            <tr>
	                <td>{% trans "Actions" %}</td>
	            </tr>
	        </thead>
	        <tbody>
	            <tr>
	                <td>
						{% if is_course_admin or request.user.is_superuser %}
		                    <a class="link_add link_0" href="{% url apps.trinity.views.clo.add course_id=course.id education_category_id=education_category.id %}">{% trans "Add course learning outcome" %}</a> 
		                    <span class="separator"> | </span>
		                    <button class="link_delete button_0" type="submit">{% trans "Delete selected" %}</button>
							<span class="separator"> | </span>
						{% endif %}
						<a class="link_print link_0" href="{% url apps.trinity.views.clo.print_pdf course_id=course.id education_category_id=education_category.id %}" target="_blank">{% trans "Print" %}</a>
	                </td>
	            </tr>
	        </tbody>
	    </table>
		<div class="spacer_5"></div>
	
	    <div id="ee_show">
	    	{% if clos %}
	    		<table class="table_0 row_highlight">
	    			<thead>
	    				<tr>
	    					{% if is_course_admin or request.user.is_superuser %}
	    						<td class="delete"></td>
	    					{% endif %}
	    					<td class="symbol">
	    						{% trans "Symbol" %}
	    					</td>
	    					<td class="description left">
	    						{% trans "Description" %}
	    					</td>
	    					{% if not course.is_level_phd and not course.is_level_pg_q and not course.is_level_pg_fl %}
	    						<td class="alo">
	    					   		{% trans "Learning outcomes for areas" %}
	    					   	</td>
	    					{% endif %}
	    					<td class="module">
	    						{% trans "Modules" %}
	    					</td>
	    				</tr>
	    			</thead>
	    			<tbody>
	    				{% for clo in clos %}
		    				<tr class="{% cycle 'odd' 'even' %}">
		    					{% if is_course_admin or request.user.is_superuser %}
			    					<td class="delete">
			    						<input type="checkbox" value="{{ clo.id }}" name="selected_id" />
			    					</td>
			    				{% endif %}
		    					<td class="symbol">
		    						{% if is_course_admin or request.user.is_superuser %}
		    							<a class="link_edit link_0" href="{% url apps.trinity.views.clo.update course_id=course.id education_category_id=education_category.id clo_id=clo.id %}">{{ clo.symbol }}</a>
		    						{% else %}
		    							<span>{{ clo.symbol }}</span>
		    						{% endif %}
		    					</td>
		    					<td class="description">
		    						{{ clo.description|linebreaksbr }}
		    					</td>
		    					{% if not course.is_level_phd and not course.is_level_pg_q and not course.is_level_pg_fl %}
		        					<td class="alo">
		        						<ul class="alos_list">
		        							{% for alo in clo.alos.all %}
		        								<li>
		        									<a href="" class="tip" title="{{ alo.description }}">
		        										{{ alo }}
		        									</a>
		        								</li>
		        							{% endfor %}
		        						</ul>
		        					</td>
		        				{% endif %}
		    					<td class="module">
		    						<ul class="modules_list">
		    							{% for module in clo.get_related_modules %}
		    								<li>
		    									<a class="link_0" href="{% url apps.trinity.views.mlo.show module.get_course.id module.get_sgroup.id module.id %}" target="_blank">{{ module }}<a/> ({% get_intensity clo module %})
		    								</li>
		    							{% endfor %}
		    						</ul>
		    					</td>
		    				</tr>
	    	        	{% endfor %}
	    			</tbody>
	    		</table>
	    		<div class="spacer_5"></div>
	    	{% else %}
				<ul class="infolist">
	    			<li>
	    				{% trans "List of learning outcomes is empty." %}
	    			</li>
	    		</ul>
	    	{% endif %}
		</div>
	</form>
	
    {% if is_course_admin or request.user.is_superuser %}
	    {% if not course.is_level_phd %}
	        {% if remaining_alos %}
	            <table class="table_0">
	                <thead>
	                    <tr>
	                        <td>
	                        	{% trans "List of unused learning outcomes for areas" %}
	                        </td>
	                    </tr>
	                </thead>
	                <tbody>
	                    <tr>
	                        <td>
	                        {% for remaining_alo in remaining_alos %} 
								<a href='' class='tip' title='{{ remaining_alo.description }}'>{{ remaining_alo.symbol }}</a>{% if not forloop.last %}, {% endif %}
	                        {% endfor %}
	                        </td>
	                    </tr>
	                </tbody>
	            </table>
	        {% else %}
	            <div class="messages">
	                <ul class="success">
	                    <li>
	                    	{% trans "All learning outcomes for areas were used." %}
	                    </li>
	                </ul>   
	            </div>
	        {% endif %}
	        <div class="spacer_5"></div>
	    {% endif %}
	{% endif %}

{% endblock %}